base_url = "https://donovan.is"
title = "Donovan Glover"
author = "Donovan Glover"
description = "Personal website of Donovan Glover, a Software Engineer based in Atlanta, GA. Specializes in Linux, Rust, and full-stack web development."
default_language = "en"
theme = "tabi-turbo"
compile_sass = true
minify_html = true
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", feed = true }
]

[markdown]
highlight_code = true
highlight_theme = "css"
external_links_target_blank = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
base_canonical_url = "https://donovan.is"
skin = "vibrance"
quick_navigation_buttons = true
long_date_format = "%B %-d %Y"
short_date_format = "%b %-d %Y"
email = "aGlAZG9ub3Zhbi5pcz9zdWJqZWN0PUhlbGxvISZib2R5PUhpIERvbm92YW4hIFNvIEkgd2FzIGNoZWNraW5nIG91dCB5b3VyIGJsb2cgYW5kLi4u"
invert_title_order = true
browser_theme_color = "#5b5b65"
menu = [
    { name = "blog", url = "blog/" },
    { name = "projects", url = "projects/" },
    { name = "about", url = "about/" },
]
socials = [
    { name = "github", url = "https://github.com/donovanglover", icon = "github" },
    { name = "linkedin", url = "https://linkedin.com/in/donovanglover", icon = "linkedin" },
]
remote_repository_url = "https://github.com/donovanglover/donovan.is"
remote_repository_branch = "master"
